### ISSUE TITLE
refactor(client): extraire le client data.gouv.fr du dépôt

### ISSUE THREAD

**Issue by maukoquiroga** [ecolabdata/ecospheres-front#105]
Superceded by #109

### Job story

> User: dév.
>
> Lorsque nous nous préparons à lancer "Écosphères Beta",
> nous voulons être en mesure de déployer en continu,
> afin de pouvoir les mettre entre les mains des utilisateurs le plus rapidement possible.

### Contexte ou situation

Quand je visite regarde le code et veux développer une fonctionnalité, je m'attends à ce que la séparation entre les différentes partie du code suive une séparation selon les meilleures pratiques pour développer facilement et avoir une base solide.

### Problème rencontré par les utilisateurs

Ce n'est pas le cas.

### Proposition de solution au problème

- Extraire le client data.gouv.fr du dépôt

### Additional elements of my proposal

- #92 
- ecolabdata/datagouvfr#1

### Definition of done

- Le code concernant le client qui gère les appels à l'API data.gouv.fr a été rapatrié.

### Related OKR

N/A.

**Comment by streino** [comment]
Je préfère qu'on garde tout dans le même repo à ce stade. C'est beaucoup plus simple à gérer dans un monorepo.
Aussi, ne pas oublier que le repo va probablement être transmis à data.gouv à terme, donc c'est un avantage de garder un "small footprint".

**Comment by maukoquiroga** [comment]
> Je préfère qu'on garde tout dans le même repo à ce stade. C'est beaucoup plus simple à gérer dans un monorepo. Aussi, ne pas oublier que le repo va probablement être transmis à data.gouv à terme, donc c'est un avantage de garder un "small footprint".
> 
> Par ailleurs, je souhaite qu'on discute en amont des manips telles que la création de repo. "ecolabdata" est une orga qui couvre l'ensemble de l'Ecolab, pas seulement le projet Ecosphères. Vous avez la main sur "ecospheres-front" mais pas le reste.

Entendu. Si l'on peut juste laisser cela ouvert le temps qu'on rappatrie ces changements ici.

**Comment by bonjourmauko** [comment]
Pour info (via @abulte) https://github.com/cdugeai/datagouv-ts
