### ISSUE TITLE
feat(nav): découvrir les bouquets par chantier

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres-front#116]
Depends on #81
Depends on #82
Depends on #115

### Job story

> Titre : Naviguer les bouquets.
> Utilisateur :  agent / consommateur de données.
>
> Lorsque je dois rédiger un rapport,
> je veux savoir quels sont les indicateurs pertinents pour le sujet du rapport,
> afin de mieux remplir ma mission de service public.

### Contexte ou situation

Lorsque j'arrive dans la landing page,
et que je clique sur une thématique,
je m'attends à pouvir en chosir un chantier,
et à voir les bouquets correspondants à ces thématiques + chantier.

### Problème rencontré par les utilisateurs

Ce n'est pas le cas.

### Proposition de solution au problème

> Je vois une liste de sept thématiques (consommer, se nourrir, ...)
> Et je fais clique sur « Se loger ».
> Et je fais clique sur « Aménagement des villes »,
> Et je vois une liste de bouquets des données, dont un avec les informations suivantes :
> ==> En haut, le nom du chantier : « Aménagement des villes »
> ==> En bas, le nom du bouquet : « Îlot de chaleur urbain »

![Nav 1](https://github.com/ecolabdata/ecospheres-front/assets/329236/492b6e43-6044-4815-9dd4-3b10fc3f9cea)

![Nav 2](https://github.com/ecolabdata/ecospheres-front/assets/329236/37c1867a-d03e-4488-9b9c-cec236277840)

![Nav 3](https://github.com/ecolabdata/ecospheres-front/assets/329236/561aa3e7-fab1-486e-a1b8-4747bdc57229)

### Éléments supplémentaires de ma proposition

> Quand je fais clique sur « Aménagement des villes », mais que je voulais faire clique sur un autre chantier, je vois un lien type « fil d'Ariane » qui est visiblement cliquable pour revenir à l'écran précédent.

> À gauche en bas, je vois un select avec le label « Chantier » et « Aménagement des villes » sélectionné. Quand je sélectionne un autre chantier, la liste de bouquets et mise à jour.

> À gauche en haut, je vois un select avec le label « Thématique » et « Se loger » sélectionné. Quand je sélectionne « Consommer », je vois la liste de chantiers correspondants à « Consommer » remplacer la liste de bouquets.

> Quand je ne retrouve pas le bouquet que je cherche parmi la liste, je vois un bouton « Créer un nouveau bouquet ».

> Quand la liste est vide, je vois un message indiquant qu'il n'y a pas encore de bouquets pour ces critères, mais d'en créer un si je le souhaite en cliquant sur le bouton « Créer un bouquet ».

#### UPDATE 2023-11-23

- Mettre le breadcrumb en haut
- Changer créer un bouquet en bouton
- Le breadcrumb doit revenir sur les filtres et pas sur la « naviation » initiale

### Définition of done

- Une application de prévisualisation déployée où tester cette fonctionnalité

### OKR associé

TODO.

**Comment by edelagnier** [comment]
Question : 


![Image](https://github.com/ecolabdata/ecospheres-front/assets/20337428/398732cf-8538-4e63-861c-cbe80ff2ef53)

Pendant mes tests je me rends compte que certain bouquets ont un sous-theme qui ne correspond pas à leur théme.

Quel comportement voulez vous adopter ? Faut il afficher tous les bouquets déclaré dans le chantier "Nucléaire" ou seulement ceux dont on peut vérifier qu'il sont bien dans la thématique "Produire" ?

**Comment by bonjourmauko** [comment]
@edelagnier Pour moi :

1. Déjà, c'est un bug sur une invariante du domaine : https://github.com/ecolabdata/ecospheres-front/blob/main/configs/ecospheres/config.yaml
2. Indépendament de cela, je pense que filtre est bien `theme === 'a' && subTheme === 'b` dans tous les cas (puisque c'est un arbre, le lien de parentalité du subTheme est important).

**Comment by bonjourmauko** [comment]
C'est peut-être un effet de bord de https://github.com/ecolabdata/ecospheres-front/issues/153 ?

**Comment by streino** [comment]
> 2\. Indépendament de cela, je pense que filtre est bien `theme === 'a' && subTheme === 'b` dans tous les cas (puisque c'est un arbre, le lien de parentalité du subTheme est important).

Je confirme :)
