### ISSUE TITLE
Explorer les bouquets par « chantier »

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres-front#119]

**Comment by streino** [comment]
Quelle différence avec https://github.com/ecolabdata/ecospheres-front/issues/116 ?

**Comment by bonjourmauko** [comment]
Hello, en suivant les maquettes Figma, il y une entrée directement par chantier (en plus de thématique, territoire, et origanisation). #116 c'est en réalité par thématique -> chantier.

**Comment by streino** [comment]
Je comprends pas bien, pour moi entrée directement par chantier n'a pas de sens.
Tu peux mettre un screenshot du figma en question ?

**Comment by bonjourmauko** [comment]
> Je comprends pas bien, pour moi entrée directement par chantier n'a pas de sens. On sélectionne forcément une thématique (Se loger, ...) avant puisque la liste de chantiers dépend de la thématique.
> 
> Tu peux mettre un screenshot du figma en question ?

Pour moi non plus, je pense que cela viens d'un vieux figma. Je ferme l'issue.

![Accueil](https://github.com/ecolabdata/ecospheres-front/assets/329236/aac0d847-9496-4036-a884-7e511d38c215)
