### ISSUE TITLE
feat(bouquet): changer « accéder à la donnée » par « accéder au catalogue »

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres-front#150]
#### Créer un bouquet

Utilisateur: agent / producteur de données

Quand je veux partager les données nécessaires pour réaliser des indicateurs,
Je veux pouvoir maintenir un même catalogue au même endroit,
Pour que d'autres puissent s'en servir et l'améliorer.

#### Naviguer les bouquets

Utilisateur: agent / consommateur de données

Lorsque je dois rédiger un rapport,
je veux savoir quels sont les indicateurs pertinents pour le sujet du rapport,
afin de mieux remplir ma mission de service public.

### Context or situation

Quand je vois les données dans un bouquet,
Je veux qu'il soit clair où vont me mener les boutons « Accéder ».

### Problem encountered by users

Ce n'est pas le cas, puisque « Accéder à la donnée » peut bien vouloir dire télécharger la donnée, etc.

### Proposal of how to solve the problem

Au lieu de :

<img width="248" alt="Screenshot 2023-11-09 at 09 49 45" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/e4be92e9-fa78-4e0f-b214-aebdabdd6ecf">

Je vois « Accéder au catalogue » :

<img width="612" alt="Screenshot 2023-11-23 at 10 20 50" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/4ad94ec4-b60d-4960-a2b9-d05565d0adc9">

**Comment by streino** [comment]
Done ?

**Comment by bonjourmauko** [comment]
Yes !
