### ISSUE TITLE
Accordions ouverts par défaut

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres-front#151]
### Job story

> Title : _title_
> User: _user_
>
> When I _situation_,
> I want to _motivation_,
> so to _expected outcome_.

### Context or situation

When I _do this_, I expect _that_ to happen.

### Problem encountered by users

It doesn't.

### Proposal of how to solve the problem

> I see _this_,
> And I do _that_,
> And then _something_ happens.

<img width="977" alt="Screenshot 2023-11-09 at 09 49 22" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/c39c95d5-e899-4e49-893d-7d8d9bd1f264">

### Additional elements of my proposal

> Some

> Additional

> Likely scenarios

### Definition of done

- A deployed preview app where to test the aforesaid
- A test suite covering the aforesaid

### Related OKR

TODO.

---

### What I did

_Write here._

### What I expected to happen

_Write here._

### What actually happened

_Write here._

### Data (or links to it) that can help you reproduce this issue

_Write here._

---

## Other

_Write here._

**Comment by streino** [comment]
C'est en cours il me semble ? Si oui lier à la PR concernée (@YeLnatSs il me semble)
