### ISSUE TITLE
bug(bouquet): validation manquante quand chantier est vide

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres-front#153]
### What I did

I created a bouquet without selecting the "chantier".

### What I expected to happen

Not to be able to.

### What actually happened

I was.

### Data (or links to it) that can help you reproduce this issue

https://github.com/ecolabdata/ecospheres-front/pull/110/files/ea0ec7e6d4b717af56482563e1d523d410e53341#r1387012139

**Comment by streino** [comment]
C'est fait ça non ?

**Comment by bonjourmauko** [comment]
Au moment où ce ticket a été créé, cette validation n''était pas en place. Je n'ai pas depuis vérifié que ce soit bien le cas maintenant.

**Comment by bonjourmauko** [comment]
Je confirme que cela marche bien maintenant :

<img width="737" alt="Screenshot 2023-11-23 at 10 13 56" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/ad4077ae-bc25-4064-9567-0d8c22a69e48">
