### ISSUE TITLE
chore: nettoyer les anciens bouquets

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres-front#159]
Depuis #110, la plupart des bouquets sont en erreur, par exemple https://ecospheres.netlify.app/bouquets/un-bouquet-avec-jdd-plzs.

En effet, la manière de stocker les informations du bouquet dans le Topic a changé de manière cassante.

Il faudrait supprimer les bouquets de démo qui ne correspondent pas au nouveau standard (liste via API + test property extras ? + DELETE).

**Comment by bonjourmauko** [comment]
C'est fait non @streino ?

**Comment by streino** [comment]
Tout à fait !
