### ISSUE TITLE
build(npm): problèmes config TS dans IDE

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres-front#175]
Mon IDE (vscode) se plaint à différents niveaux de la config TS introduite par #170.

### `tsconfig.json`

J'ai essayé de supprimer `dist/*` mais les erreurs persistent.

<img width="762" alt="Capture d’écran 2023-11-22 à 15 23 42" src="https://github.com/ecolabdata/ecospheres-front/assets/119625/f8ed3ef9-83fe-4a18-a661-52fc7910d424">
<img width="770" alt="Capture d’écran 2023-11-22 à 15 23 36" src="https://github.com/ecolabdata/ecospheres-front/assets/119625/2e1d01d3-5e59-4da2-a2cc-c24c0a763204">

### `vite.config.ts`

Fix simple: revenir `vite.config.js`, TS n'a aucun intérêt ici.

<img width="983" alt="Capture d’écran 2023-11-22 à 15 23 51" src="https://github.com/ecolabdata/ecospheres-front/assets/119625/4a52dd5b-fe53-43ee-9edc-0dc299f5ebc7">

**Comment by edelagnier** [comment]
Je viens de merge main sur ma branch et ai les même erreurs. 
A premiere vue elles disparaissent avec ces fix : https://github.com/ecolabdata/ecospheres-front/commit/57332a12f37d92a93042986ee7e4886610871dc2

Je vais continuer a travailler un peu dans cette conf pour voir s'il y a des effet indésirables

**Comment by bonjourmauko** [comment]
@abulte Étrange, j'ai testé sur neo/vim et WebStorm (PyCharm) et ça marche très bien. En particulier, avec la config actuelle, `npm run hint` (tsc) n'a plus de problèmes de parsing. Es-tu sûr qu'il ne faut pas une config spéciale pour VSCode ?

**Comment by bonjourmauko** [comment]
(Dans tous les cas, comme hotfix, pas de soucis de laisser cela en js, mais cela devrait marcher en ts, donc soit la config est incomplète, soit il y a un soucis avec vscode, ou les deux).

**Comment by streino** [comment]
Ok pour le revert .ts -> .js
@edelagnier tu as mentionné avoir des problèmes aussi depuis le merge. Tu as fais d'autres modifs ou on part là dessus ?

**Comment by bonjourmauko** [comment]
Et c'est bien en `ts`, problème de conf alors.
