### ISSUE TITLE
feat(style): adopter le bleu data.gouv.fr ✨ 

### ISSUE THREAD

**Issue by geoffreyaldebert** [ecolabdata/ecospheres-front#195]
## Demande de fonctionnalité

Le bleu Dsfr n'est pas exactement le bleu que nous utilisons côté data.gouv.fr. Il s'agit du bleu #060091 tandis que nous utilisons le #3558A2 (avec des bleus en hover différents également).

Harmonisez l'ensemble des bleus de la stack applicative pour coller au bleu data.gouv.fr

Cc @agarrone @streino

**Comment by Jorek57** [comment]
On fait ça de manière simple en le modifiant en "dur" partout ou on laisse la possibilité de le modifier à loisir dans les configs propres à chaque domaine ?
