### ISSUE TITLE
Moissonnage de catalogues exposés via API

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres-front#20]
### Besoin

Exemple : Catalogue de l'Ademe (Koumoul)

**Comment by abulte** [comment]
Ce catalogue est déjà "moissonné" par data.gouv.fr : l'ADEME pousse ses jeux de données sur data.gouv.fr via l'API. Ecosphères peut donc les récupérer via l'api de data.gouv.fr.

Ou j'ai raté une subtilité ?

**Comment by streino** [comment]
@Thesauruv ⬆️

**Comment by streino** [comment]
Je ferme le ticket, on fera un point plus général lorsqu'on aura clarifié la situation autour du périmètre et des moissonnages.
