### ISSUE TITLE
Topic: search by technical id

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres-front#49]
The current search expects a `slug` when passing `topic={param}` to `/search/datasets`. Slugs being subject to change, it would be nice to be able to _also_ pass a technical id.

**Comment by maudetes** [comment]
Could we replace by `id` only or do you need *both*? Seems to be `id` only for organization [for example](https://www.data.gouv.fr/api/2/datasets/search/?organization=etalab).

**Comment by maudetes** [comment]
Done in https://github.com/opendatateam/udata/pull/2901
(Need to wait for deployment and re-indexing)

**Comment by streino** [comment]
Working now!
