### ISSUE TITLE
feat(bouquet): créer un bouquet

### ISSUE THREAD

**Issue by maukoquiroga** [ecolabdata/ecospheres-front#60]
### Here's the job story

> Title : Data bouquets
> User: Ecolab
>
> When we're about to launch "Écosphères Bêta", 
> we want to create data bouquets,
> so to encourage data re-use and discoverability by use case.

### Here is the context or situation

When I visit "Vertical Ecosphères", I go to the "bouquets" tab expecting to find the bouquet I'm looking for.

### Here is the problem encountered by users

There is no such bouquet.

### Here is a proposal of how to solve the problem

> I log in with my (demo) data.gouv.fr user and password,
> I come back to the "bouquets" tab,
> And I click on the "Ajouter un bouquet" link/button,
> I fill in "Objectif du bouquet" with the name of the bouquet,
> I fill in "Comment utiliser ce bouquet" with the description of the bouquet
> (I use markdown to format the text into several headings),
> I click "Enregistrer" (a blue button),
> I'm redirected to the bouquet I just created,
> And I can read a success message telling me it all worked seamlessly.

![Image](https://github.com/ecolabdata/ecospheres-front/assets/329236/379639e4-7a85-405e-9488-f13dd9889913)

### Here are some additional elements of my proposal

> I can clearly see what fields are required

> If I fail to provide a required field, I'm told so and prevented from creating the bouquet

> If I don't undestand what to fill in the "Objectif du bouquet field", the tooltip to the right provides help

> If I don't undestand what to fill in the "Comment utiliser ce bouquet", the tooltip to the right provides help

> If for any reason the creation does not succeed, I have a clear alert message telling me to open an issue and a link to https://github.com/ecolabdata/ecospheres-front/issues/new

### Here's the definition of done

- A deployed preview app where to test the aforesaid
- A test suite covering the aforesaid

### Here's the related OKR

TODO.

**Comment by YeLnatSs** [comment]
Hi @maukoquiroga ,
I don't really understand what I am supposed to do because the creation part has already been created. Only the design is not similar to the model

**Comment by maukoquiroga** [comment]
@ecolabdata/ecospheres In the design, to the right, there's a tooltip for each field. However, I could not find it in the Figma (I bet you pardon it is there). Do you have the text to add to each tooltip?

**Comment by martyKN** [comment]
we don't have the text yet for the tooltips, but we can work on it very quickly

**Comment by maukoquiroga** [comment]
@martyKN The other question we had was concerning  the "Comment utiliser ce bouquet" that accepts markdown. Should we follow the design on that one and add a styling editor component?

**Comment by YeLnatSs** [comment]
With the dsfrInput component, it's not possible to implement the wisywig system.

**Comment by maukoquiroga** [comment]
Merci @YeLnatSs . D'après ce que l'on s'est dit —ne pas sortir du DSFR pour l'instant— je propose qu'on reste sur un input classique. Nous pourrons évaluer un peu plus tard si l'on s'investit sur ce composant. @martyKN est-ce que cela t'irait si l'on ajoute, par exemple en description de l'input, une phrase du type: « Utilisez des #, ##, et ### pour créer des titres ».

**Comment by maukoquiroga** [comment]
Si jamais on est bloqué par les alertes, je viens d'ouvrir un issue à ce sujet #92

**Comment by YeLnatSs** [comment]
@maukoquiroga plutôt bloquant pour les alertes en cas d'input vide
