### ISSUE TITLE
doc: add LICENCE/LICENSE

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres-front#68]
Note: _license_ is the standard name, and _licence_ is in British English. Now that the UK is not part of the EU, I ignore which spelling, US or UK, should generally be followed.

**Comment by streino** [comment]
I tend to go with EN/US everywhere, but I don't have it backed but with anything other than mindshare.

**Comment by maukoquiroga** [comment]
I'm OK with both as long as the use is consistent (one or the other).

**Comment by streino** [comment]
Done in https://github.com/ecolabdata/ecospheres-front/commit/5c80ba6e77636bc1549957812ecfecb63c4a2623
