### ISSUE TITLE
feat(bouquet): recap création bouquet

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres-front#79]
Depends on #85 
Depends on #86
Depends on #87

![Image](https://github.com/ecolabdata/ecospheres-front/assets/329236/ed10ec74-e511-489c-98b7-ebb5faf1c540)

**Comment by maukoquiroga** [comment]
@martyKN Quelle est la liste de valeurs possibles ?

**Comment by bonjourmauko** [comment]
Closed by #173
