### ISSUE TITLE
feat(bouquet): créer un bouquet avec thématique

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres-front#81]
Depends on #60 

### Job story

> Utilisateur : Ecolab
>
> Lorsque nous sommes sur le point de lancer "Écosphères Bêta",
> nous voulons créer des bouquets de données,
> afin d'encourager la réutilisation et la découverte des données par cas d'utilisation.

### Contexte ou situation

Lorsque je crée un bouquet sur « Verticale Ecosphères », je m'attends à pouvoir en définir la thématique.

### Problème rencontré par les utilisateurs

Ce n'est pas le cas.

### Proposition de solution au problème

> Je me connecte avec mon identifiant et mon mot de passe (démo) data.gouv.fr,
> Je reviens sur l'onglet "bouquets",
> Et je clique sur le lien/bouton "Ajouter un bouquet",
> Je renseigne "Titre du bouquet",
> Je remplis "Objectif du bouquet",
> Je clique sur "Enregistrer" (un bouton bleu),
> Je suis redirigé vers le bouquet que je viens de créer,
> Je peux lire un message de succès qui m'indique que tout s'est déroulé sans problème,
> Et je renseigne la « thématique » du bouquet en choissisant « Produire » parmi les options suivantes :
> > Produire
> > Se nourrir
> > Se loger
> > Se déplacer
> > Préserver
> > Consommer
> > Chantiers transverses

![Create 1](https://github.com/ecolabdata/ecospheres-front/assets/329236/f21ab17b-d140-4811-87fc-16cb7d7bc4ec)

![Create 2](https://github.com/ecolabdata/ecospheres-front/assets/329236/8e133060-23d1-40ec-9145-01057d3157cb)

### Éléments supplémentaires de ma proposition

Stocké dans l'API data.gouv.fr (`/topics/{topic}`), cela devrait plus ou moins se rassembler à cela :

```json
{
  "extras": {
    "scope:theme": "string",
    "scope:sub-theme": "string"
  }
}
```

### Définition de _done_

- Une application de prévisualisation déployée où tester cette fonctionnalité

### OKR associé

TODO.

**Comment by maukoquiroga** [comment]
@martyKN What is the list of possible values?
