### ISSUE TITLE
feat(bouquet): créer un bouquet avec chantier

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres-front#82]
Depends on #60

### Job story

> Utilisateur : Ecolab
>
> Lorsque nous sommes sur le point de lancer "Écosphères Bêta",
> nous voulons créer des bouquets de données,
> afin d'encourager la réutilisation et la découverte des données par cas d'utilisation.

### Contexte ou situation

Lorsque je crée un bouquet sur « Verticale Ecosphères », je m'attends à pouvoir en définir le chantier.

### Problème rencontré par les utilisateurs

Ce n'est pas le cas.

### Proposition de solution au problème

> Je me connecte avec mon identifiant et mon mot de passe (démo) data.gouv.fr,
> Je reviens sur l'onglet "bouquets",
> Et je clique sur le lien/bouton "Ajouter un bouquet",
> Je renseigne "Titre du bouquet",
> Je remplis "Objectif du bouquet",
> Je clique sur "Enregistrer" (un bouton bleu),
> Je suis redirigé vers le bouquet que je viens de créer,
> Je peux lire un message de succès qui m'indique que tout s'est déroulé sans problème,
> Et je renseigne la « thématique » du bouquet en choissisant « Produire » parmi les options suivantes :

> / Produire
> / Se nourrir
> / Se loger
> / Se déplacer
> / Préserver
> / Consommer
> / Chantiers transverses

> Quand je renseigne la « thématique », je choisis « Nucléaire » parmi les options suivantes :

> / Produire
> // Nucléaire
> // Tertiaire (incluant les bâtiments publics de l'État et des collectivités, hors logement)
> // Production d'électricité décarbonée (hors nucléaire)
> // Production d'énergie décarbonnée (hors éléctricité)
> // Prévention, gestion et valorisation des déchets
> // Transport de marchandises, logistique, e-commerce
> // Verdissement du secteur et des instruments financiers
> // Décarbonation de l’industrie

> / Se nourrir
> // Alimentation
> // Agriculture et pêche

> / Se loger
> // Construction et rénovation des logements
> // Aménagements des villes

> / Se déplacer
> // Voitures et infrastructures routières
> // Mobilité courte distance (hors voiture)
> // Mobilité longue distance (avion, train)

> / Préserver
> // Eau
> // Sols
> // Océans et mers
> // Forêt

> / Consommer
> // Consommation plus durable (ménages)
> // Numérique responsable
> // Achats durables (de l’État, des collectivités et des entreprises)

> / Chantiers transverses
> // Le financement qui permet de définir des trajectoires d’investissement crédibles et cohérentes
> // La planification et la différenciation territoriale selon les caractéristiques et les spécificités de chaque territoire, incluant les territoires ultra-marins
> // La transition des filières avec la gestion des emplois, des formations et des compétences
> // Les données environnementales
> // Les services publics exemplaires
> // La transition juste et les mesures d’accompagnement, pour ne laisser personne au bord du chemin
> // La sobriété des usages et des ressources.

![Create 1](https://github.com/ecolabdata/ecospheres-front/assets/329236/f21ab17b-d140-4811-87fc-16cb7d7bc4ec)

![Create 2](https://github.com/ecolabdata/ecospheres-front/assets/329236/8e133060-23d1-40ec-9145-01057d3157cb)

### Éléments supplémentaires de ma proposition

> Quand je change la « thématique », la liste possible de « chantier » change aussi.

Stocké dans l'API data.gouv.fr (`/topics/{topic}`), cela devrait plus ou moins se rassembler à cela :

```json
{
  "extras": {
    "scope:theme": "string",
    "scope:sub-theme": "string"
  }
}
```

### Définition de _done_

- Une application de prévisualisation déployée où tester cette fonctionnalité

### OKR associé

TODO.

**Comment by maukoquiroga** [comment]
@martyKN What is the list of possible values?

**Comment by martyKN** [comment]
le découpage se fait comme ci

**Comment by martyKN** [comment]
le découpage se fait comme cela
les 7 thématiques : 
1. produire
2. se nourrir
3. se loger
4. se déplacer
5. préserver
6. consommer
7. chantiers transverses

les chantiers par thématiques
**produire**
1. Nucléaire
2. Tertiaire (incluant les bâtiments publics de l'État et des collectivités, hors logement)
3. Production d'électricité décarbonée (hors nucléaire)
4. production d'énergie décarbonnée (hors éléctricité)
5. Prévention, gestion et valorisation des déchets
6. Transport de marchandises, logistique, e-commerce
7. Verdissement du secteur et des instruments financiers
8. Décarbonation de l’industrie

**se nourrir**
1. Alimentation
2. Agriculture et pêche

**se loger**
1. Construction et rénovation des logements
2. Aménagements des villes

**se déplacer**
1. Voitures et infrastructures routières
2. Mobilité courte distance (hors voiture)
3. Mobilité longue distance (avion, train)

**préserver**
1. eau
2. sols
3. océans et mers
4. forêt

**consommer**
1. Consommation plus durable (ménages)
2. Numérique responsable
3. Achats durables (de l’État, des collectivités et des entreprises)

**chantiers transverses**
1. Le financement qui permet de définir des trajectoires d’investissement crédibles et cohérentes
2. La planification et la différenciation territoriale selon les caractéristiques et les spécificités de chaque territoire, incluant les territoires ultra-marins
3. La transition des filières avec la gestion des emplois, des formations et des compétences
4. Les données environnementales
5. Les services publics exemplaires
6. La transition juste et les mesures d’accompagnement, pour ne laisser personne au bord du chemin
7. La sobriété des usages et des ressources.

**Comment by martyKN** [comment]
document de référence par rapport à ce découpage https://www.gouvernement.fr/upload/media/content/0001/04/609f1b127e9b3ab108c9bd421ad091c4af0666d5.pdf

**Comment by maukoquiroga** [comment]
Thanks @martyKN , I reopen as I'll use this issue to describe the feature request.

**Comment by streino** [comment]
`scope` est-il utile ? On prévoit de mettre quel genre d'autres choses dedans ?

**Comment by maukoquiroga** [comment]
> Après, le préfixe `scope` est-il utile ? On prévoit de mettre quel genre d'autres choses dedans ?

L'ancrage territorial ? Enfin, ce prefixe est juste dû à https://github.com/ecolabdata/ecospheres-front/issues/103#issuecomment-1772495979

**Comment by streino** [comment]
> > Après, le préfixe `scope` est-il utile ? On prévoit de mettre quel genre d'autres choses dedans ?
> 
> L'ancrage territorial ? Enfin, ce prefixe est juste dû à [#103 (comment)](https://github.com/ecolabdata/ecospheres-front/issues/103#issuecomment-1772495979)

Donc si on avait les `dict`, tu envisages au final qqch comme ça ?
```
"extras": {
  "datasets_properties": ...,
  "scope": {
    "sub-theme": ...,
    "territory": ...,
    "theme": ...
  },
  ...
}
```

Ok pour moi, même si je reste dubitatif sur l'intérêt d'avoir cette clé intermédiaire par rapport à : 
```
"extras": {
  "datasets_properties": ...,
  "sub-theme": ...,
  "territory": ...,
  "theme": ...,
  ...
}
```

Mais je n'ai pas vraiment réfléchi à la structure complète, donc je peux me tromper.
