### ISSUE TITLE
feat(bouquet): créer un bouquet avec une donnée d'une autre source que data.gouv.fr

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres-front#86]
Depends on #81 
Depends on #82

### Job story

> Utilisateur : Ecolab
>
> Lorsque nous sommes sur le point de lancer "Écosphères Bêta",
> nous voulons créer des bouquets de données,
> afin d'encourager la réutilisation et la découverte des données par cas d'utilisation.

### Contexte ou situation

Lorsque je crée un bouquet sur « Verticale Ecosphères », je m'attends à pouvoir rajouter des cas d'utilisation des données.

### Problème rencontré par les utilisateurs

Ce n'est pas le cas.

### Proposition de solution au problème

> Je me connecte avec mon identifiant et mon mot de passe (démo) data.gouv.fr,
> Je reviens sur l'onglet "bouquets",
> Et je clique sur le lien/bouton "Ajouter un bouquet",
> Je renseigne "Titre du bouquet",
> Je remplis "Objectif du bouquet",
> Je clique sur "Enregistrer" (un bouton bleu),
> Je suis redirigé vers le bouquet que je viens de créer,
> Je peux lire un message de succès qui m'indique que tout s'est déroulé sans problème,
> Et je renseigne la « thématique » du bouquet en choissisant « Produire »,
> Quand je renseigne la « thématique », je choisis le « chantier » « Nucléaire »,
> Maintenant, je peux rajouter un ou plusieurs cas d'utilisation des données,

> Quand je rajoute le premier, je remplis dans l'ordre:
> « Inducateurs thérmodynamiques » dans « Libellé de la donnée »,
> « Données à jour de Méteo France pour les indicateurs sous-cités » dans « Raison d'utilisation dans ce bouquet »,
> Je cherche « Indicateurs thermodynamiques », mais je ne le trouve pas,

> Je cherche donc l'URL dans mes notes (dans mon ordinateur)
> Et je remplis "Vous ne toruvez pas la donnée dans Écosphères" avec l'URL que j'ai copié de mon LibreCalc (o Excel)

> Je clique en « Ajouter la donnée »,
> Et je peux voir qu'elle aparaisse  sous « Données selectionnées (1) »,
> Avec le libellé, la raison en guise de description, et un lien vers le catalogue source.

> Je clique suivant
> Je vois une alerte verte m'indiquant que tout a bien marché
> Et je peux voir les détails du bouquet

![Create 1](https://github.com/ecolabdata/ecospheres-front/assets/329236/0f23418e-c166-4d56-abf1-beebfa33c9bd)

![Create 2](https://github.com/ecolabdata/ecospheres-front/assets/329236/0c0f38a4-cfe7-4199-bc6b-922a8650f84c)

![Create 3 2](https://github.com/ecolabdata/ecospheres-front/assets/329236/f57cb982-2cf4-4cb6-a6e9-deae83cf0e63)

![Create 4](https://github.com/ecolabdata/ecospheres-front/assets/329236/7d849d89-334e-4a68-8d3c-018103ceb16a)

### Éléments supplémentaires de ma proposition

> Quand j'oublie de remplir le libellé, j'ai un message d'erreur quand je veux ajouter la donnée (alerte)

> Quand j'oublie de remplir la raison, j'ai un message d'erreur quand je veux ajouter la donnée (alerte)

> Quand je me trompe de donnée, je peux chercher à nouveau grâce à la barre de recherche

> Quand je clique « Retirer de la sélection », ce cas d'utilisation disparaît

> Quand je veux rajouter plusiers datasets dans un même `DatasetProperties`,
> je vois un texte assez visible m'indiquant que c'est seulement un dataset par `DatasetProperties`.

Stocké dans l'API data.gouv.fr (`/topics/{topic}`), cela devrait plus ou moins se rassembler à cela :

```json
{
  "datasets": [
    {
      "id": "Id du dataset sur data.gouv.fr"
    }
  ],
  "extras": {
    "datasets_properties": [
      {
        "title": "Libellé du dataset properties (celui que j'ai rempli, pas celui du dataset",
        "description": "Raison d'utilisation du dataset dans ce bouquet, (celui que j'ai rempli, pas celui du dataset)",
        "id": "Id du dataset sur data.gouv.fr (dans cet exemple, le même que plus haut)",
        "uri": "Optionnellement, un uri vers un autre catalogue, si je ne retrouve la donnée sur datagouv",
        "available": true,
      }
    ]
  }
}
```

Le champ `available` fait référence à si le dataset est disponible pour être utilisé. Par exemple, un dataset properties peut pointer vers un dataset fermé, auquel cas `available` est `false`. Pareillement, `available` peut être `true` sans qu'il y ait pour autant ni de `id` ni de `uri`, auquel cas on peut considérer la donnée comme `manquante` (`missing`).

### Définition de _done_

- Une application de prévisualisation déployée où tester cette fonctionnalité

### OKR associé

TODO.

**Comment by maukoquiroga** [comment]
Si sur data.gouv.fr :
- name
- uri

Si pas sur data.gouv.fr :
- uri
- name?
