### ISSUE TITLE
feat(bouquet): créer un bouquet avec une donnée non disponible

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres-front#87]
Depends on #81 
Depends on #82

### Job story

> Utilisateur : Ecolab
>
> Lorsque nous sommes sur le point de lancer "Écosphères Bêta",
> nous voulons créer des bouquets de données,
> afin d'encourager la réutilisation et la découverte des données par cas d'utilisation.

### Contexte ou situation

Lorsque je crée un bouquet sur « Verticale Ecosphères », je m'attends à pouvoir rajouter des cas d'utilisation des données.

### Problème rencontré par les utilisateurs

Ce n'est pas le cas.

### Proposition de solution au problème

> Je me connecte avec mon identifiant et mon mot de passe (démo) data.gouv.fr,
> Je reviens sur l'onglet "bouquets",
> Et je clique sur le lien/bouton "Ajouter un bouquet",
> Je renseigne "Titre du bouquet",
> Je remplis "Objectif du bouquet",
> Je clique sur "Enregistrer" (un bouton bleu),
> Je suis redirigé vers le bouquet que je viens de créer,
> Je peux lire un message de succès qui m'indique que tout s'est déroulé sans problème,
> Et je renseigne la « thématique » du bouquet en choissisant « Produire »,
> Quand je renseigne la « thématique », je choisis le « chantier » « Nucléaire »,
> Maintenant, je peux rajouter un ou plusieurs cas d'utilisation des données,

> Quand je rajoute le premier, je remplis dans l'ordre:
> « Inducateurs thérmodynamiques » dans « Libellé de la donnée »,
> « Données à jour de Méteo France pour les indicateurs sous-cités » dans « Raison d'utilisation dans ce bouquet »,
> Je cherche « Indicateurs thermodynamiques », mais je ne le trouve pas,

> Je cherche donc l'URL dans mes notes (dans mon ordinateur)
> Mais je ne le trouve pas non plus parce que mon PC est en panne ce matin,
> Et je ne remplis donc pas « Retrouver la donnée via »

> Je clique en « Ajouter la donnée »,
> Et j'ai un message d'information m'indiquant de faire un choix pour « Retrouver la donnée via ».

> Je choisis donc « Je n'ai pas trouvé la donnée »,
> je clique en « Ajouter la donnée »,
> Et je peux voir qu'elle aparaisse  sous « Composition du bouquet (1) »,
> Avec le libellé, la raison en guise de description, un lien « Aidez-nous à trouver la donnée »,
> Et avec une pastille m'indiquant que la donnée es une « donnée non-disponible ».

> Je clique suivant
> Je vois une alerte verte m'indiquant que tout a bien marché
> Et je peux voir les détails du bouquet

![Create 1](https://github.com/ecolabdata/ecospheres-front/assets/329236/927f5397-f00c-4861-a5ed-a22a62600d57)
![Create 2](https://github.com/ecolabdata/ecospheres-front/assets/329236/0232d9cd-89c6-46ce-9c36-bed488db3595)
![Create 3 3](https://github.com/ecolabdata/ecospheres-front/assets/329236/5ebfe8ec-9f0b-4106-a21d-7864e3317ba5)
![Create 4](https://github.com/ecolabdata/ecospheres-front/assets/329236/4002dff1-88c8-425e-bc12-746edd4ce3ad)

### Éléments supplémentaires de ma proposition

> Quand j'oublie de remplir le libellé, j'ai un message d'erreur quand je veux ajouter la donnée (alerte)

> Quand j'oublie de remplir la raison, j'ai un message d'erreur quand je veux ajouter la donnée (alerte)

> Quand je me trompe de donnée, je peux chercher à nouveau grâce à la barre de recherche

> Quand je clique « Retirer de la sélection », ce cas d'utilisation disparaît

> Quand je veux rajouter plusiers datasets dans un même `DatasetProperties`,
> je vois un texte assez visible m'indiquant que c'est seulement un dataset par `DatasetProperties`.

> Quand je clique « Aidez-nous à trouver la donnée »,
> mon client email s'ouvre avec un nouvel email pre-rempli,
> avec comme destinataire « ecospheres@developpement-durable.gouv.fr »
> et comme message « Information concernant une donnée non disponible ou manquante »

Stocké dans l'API data.gouv.fr (`/topics/{topic}`), cela devrait plus ou moins se rassembler à cela :

```json
{
  "datasets": [
    {
      "id": "Id du dataset sur data.gouv.fr"
    }
  ],
  "extras": {
    "datasets_properties": [
      {
        "title": "Libellé du dataset properties (celui que j'ai rempli, pas celui du dataset",
        "description": "Raison d'utilisation du dataset dans ce bouquet, (celui que j'ai rempli, pas celui du dataset)",
        "id": "Id du dataset sur data.gouv.fr (dans cet exemple, le même que plus haut)",
        "uri": "Optionnellement, un uri vers un autre catalogue, si je ne retrouve la donnée sur datagouv",
        "available": "not available",
      }
    ]
  }
}
```

Le champ `available` fait référence à si le dataset est disponible pour être utilisé. Par exemple, un dataset properties peut pointer vers un dataset fermé, auquel cas `available` est `false`. Pareillement, `available` peut être `true` sans qu'il y ait pour autant ni de `id` ni de `uri`, auquel cas on peut considérer la donnée comme `manquante` (`missing`).

### Définition de _done_

- Une application de prévisualisation déployée où tester cette fonctionnalité

### OKR associé

TODO.

**Comment by maukoquiroga** [comment]
« Je n'ai pas trouvé la donnée »
