### ISSUE TITLE
Add a linter and formatter config

### ISSUE THREAD

**Issue by maukoquiroga** [ecolabdata/ecospheres-front#88]
### Here's the job story

> User: Multi + Ecolab
>
> When we are getting ready to launch "Écosphères Beta",
> we want to be able to roll out each changeset continuously,
> so that we can get them into the hands of users as quickly as possible.

### Here is the context or situation

When I code, I don't want to choose what style to adhere to.
When I review code, I don't want to do a style review.

### Here is the problem encountered by users

Currently, we have to.

### Here is a proposal of how to solve the problem

Add a linter and formatter config

### Here are some additional elements of my proposal

A discussion on [StackExchange](https://softwareengineering.stackexchange.com/questions/2756/how-important-are-code-formatting-guidelines)

### Here's the definition of done

- Code can be linted with `npm run lint`
- Code can be formatted with `npm run format`

### Here's the related OKR

N/A.

**Comment by streino** [comment]
On va attendre pour merger.
@geoffreyaldebert prépare une PR de son fork, si on change le formatage de notre côté on va lui compliquer la vie.
Normalement on devrait y voir plus clair la semaine prochaine 🤞
